
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 112
#define YY_END_OF_BUFFER 113
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[386] =
    {   0,
        0,    0,    0,    0,    0,    0,  113,  111,    4,    3,
        2,    3,    1,   38,   10,  104,   37,  111,   44,   45,
       35,   33,   40,   34,  111,   36,  110,  110,   41,   32,
       30,   31,  104,  104,   46,   47,   39,  104,  104,  104,
      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,
      104,  104,  104,   42,  111,   43,    8,    7,    7,    8,
       15,   13,   13,   14,   12,    3,   22,  104,   27,   19,
       20,   29,  107,    0,    6,    5,  106,    0,    0,    0,
      110,    0,   26,   24,   21,   23,   25,  104,  104,  104,
      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,

      101,  104,  104,  104,  104,  104,  104,  104,  104,   48,
      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  104,  104,  104,  104,  104,  104,   28,
        7,    9,   13,   12,   11,  107,    0,    0,    0,    5,
      107,    0,    0,  105,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  104,  104,   76,  104,  104,  104,   56,
      104,  104,   83,  104,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  104,  104,  104,  104,  104,  104,   92,
      104,  104,  104,    0,  109,    0,  107,    0,    0,    0,

      108,  105,    0,  104,  104,  104,  104,  104,  104,  104,
       66,   67,  104,   69,  104,  104,  104,  104,  104,   49,
       71,  104,  104,  104,  104,  102,  104,  104,  104,  104,
       81,  104,   62,  104,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  104,   88,  104,  104,   60,   55,  104,
      104,  109,    0,    0,    0,  108,  108,    0,  104,  104,
      104,  104,  104,  104,   65,   68,   54,   70,  104,  104,
      104,  104,   61,   73,   75,  104,  104,  104,  104,  104,
      104,  104,  104,  104,  104,   85,  104,  104,   87,  104,
      104,   89,  104,  104,   50,    0,  108,    0,  104,   59,

       64,  104,   97,  104,  104,  104,   57,  104,  104,  104,
       78,  104,  104,   82,  104,  104,  104,   53,   51,   52,
      104,   96,  104,   90,  104,  104,   18,   63,    0,  104,
       58,  104,   98,   72,   74,  104,  104,  104,   99,  103,
      104,  104,  104,  104,  104,    0,    0,   94,   95,  104,
      104,  104,  104,   86,  104,  104,   93,    0,    0,  104,
      104,   80,   84,  104,   91,    0,    0,   77,   79,  104,
        0,    0,  104,    0,    0,  100,    0,    0,    0,    0,
        0,    0,   17,   16,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    4,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    6,    7,    8,    1,    9,   10,   11,    1,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   21,   21,   21,   21,   21,   21,    1,   22,   23,
       24,   25,    1,    1,    9,    9,    9,    9,   26,    9,
        9,    9,   27,    9,    9,    9,    9,    9,    9,    9,
        9,    9,   28,    9,    9,    9,    9,    9,    9,    9,
       29,   30,   31,   32,   33,    1,   34,   35,   36,   37,

       38,   39,   40,   41,   42,    9,   43,   44,   45,   46,
       47,   48,    9,   49,   50,   51,   52,   53,   54,   55,
       56,   57,   58,   59,   60,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[61] =
    {   0,
        1,    1,    2,    1,    2,    1,    1,    1,    3,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        3,    1,    1,    1,    1,    3,    3,    3,    1,    1,
        1,    1,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    1,    1,    1
    } ;

static const flex_int16_t yy_base[391] =
    {   0,
        0,    0,   58,   59,   62,   63,  498,  499,  499,  499,
      499,  494,  499,  472,  499,    0,  499,  484,  499,  499,
      499,  479,  499,   52,   54,   62,   62,   76,  499,   55,
      469,   60,  446,   35,  499,  499,  499,   54,   52,   69,
       68,   73,   78,  444,   84,  443,   93,   84,  451,   83,
       91,  441,  446,  499,  427,  499,  499,  499,  482,  465,
      499,  499,  480,  499,  113,  499,  499,    0,  499,  499,
      499,  499,  127,  444,  499,    0,  129,  148,  155,  121,
      159,  162,  499,  499,  499,  499,  499,  430,  431,  429,
      428,  427,  429,  437,  423,  106,  439,  438,  425,  431,

      417,  418,  415,  415,  421,  418,  416,  413,  410,    0,
      412,  137,  413,  407,  403,  412,  419,  104,  419,  402,
      405,   56,  403,  408,  403,  129,  150,  119,  406,  499,
      499,  499,  499,  499,  499,  170,  184,  189,  401,    0,
      191,  198,  173,  200,  408,  403,  393,  392,  404,  397,
      406,  401,  400,  401,  387,  385,  175,  400,  398,  394,
      386,  392,  379,  394,  393,    0,  379,  183,  374,  386,
      383,  380,    0,  377,  377,  366,  367,  373,  364,  366,
      363,  371,  374,  360,  374,  359,  361,  361,  368,    0,
      368,  370,  359,  211,  214,  362,  216,  223,  225,  230,

      232,  235,  239,  361,  354,  361,  349,  348,  358,  352,
        0,    0,  353,    0,  343,  341,  349,  338,  345,    0,
        0,  342,  349,  342,  334,    0,  346,  334,  348,  332,
        0,  327,    0,  345,  344,  339,  334,  326,  323,  331,
      336,  322,  334,  328,    0,  314,  317,    0,    0,  315,
      327,  241,  243,  313,  246,  249,  257,  259,  325,  322,
      316,  326,  308,  324,    0,    0,    0,    0,  311,  312,
      317,  317,    0,  309,    0,  307,  300,  304,  310,  310,
      307,  295,  309,  308,  297,    0,  306,  290,    0,  299,
      290,  288,  295,  294,    0,  294,  263,  265,  285,    0,

      315,  296,    0,  285,  278,  278,    0,  278,  271,  288,
        0,  289,  290,    0,  285,  284,  270,    0,    0,    0,
      281,    0,  272,    0,  280,  273,  499,  298,  268,  263,
        0,  275,    0,    0,    0,  266,  273,  273,    0,    0,
      268,  249,  249,  248,  255,  243,  237,    0,    0,  237,
      240,  243,  238,    0,  231,  220,    0,  223,  197,  191,
      200,    0,    0,  171,    0,  174,  198,    0,    0,  176,
      157,  152,  161,  151,  124,    0,  131,  102,   92,   80,
       60,   56,  499,  499,  499,  298,  301,   84,  304,  307
    } ;

static const flex_int16_t yy_def[391] =
    {   0,
      385,    1,  386,  386,  387,  387,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  388,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  388,  388,  385,  385,  385,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  389,  385,  385,  388,  385,  385,
      385,  385,  385,  385,  385,  390,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,

      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  390,
      385,  385,  385,  385,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  385,  385,  385,  385,  385,  385,  385,

      385,  385,  385,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  385,  385,  385,  385,  385,  385,  385,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  385,  385,  385,  388,  388,

      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  385,  388,  385,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  385,  385,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  385,  385,  388,
      388,  388,  388,  388,  388,  385,  385,  388,  388,  388,
      385,  385,  388,  385,  385,  388,  385,  385,  385,  385,
      385,  385,  385,  385,    0,  385,  385,  385,  385,  385
    } ;

static const flex_int16_t yy_nxt[560] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   31,   32,   16,   33,   34,   35,    8,
       36,   37,   16,   38,   39,   40,   41,   42,   43,   44,
       16,   45,   16,   46,   16,   47,   16,   48,   49,   50,
       51,   16,   52,   53,   16,   16,   16,   54,   55,   56,
       58,   58,   59,   59,   62,   62,   63,   63,   71,   64,
       64,   60,   60,   73,   73,   75,   72,   83,   84,   77,
       76,   78,   78,   86,   87,   89,   68,   79,   91,  181,
       90,   65,   65,   77,   80,   81,   81,   74,   93,   79,

       94,   79,   96,   92,  182,  100,  384,   95,   82,   97,
      383,  105,   98,   79,  101,   99,  102,  117,  103,  106,
      135,  107,  110,  121,  108,  382,  114,  104,  111,  112,
      115,  126,  118,  122,  123,  119,  124,  381,  125,  127,
       78,   78,  135,  380,  116,  176,  136,  136,  141,  141,
      177,  135,  137,   80,  142,  153,  154,  379,  135,  138,
      191,  135,  192,  135,  137,   77,  142,   78,   78,  143,
      186,  143,  378,   79,  144,  144,   77,  187,   81,   81,
       80,   81,   81,  188,   79,   79,  169,  170,  377,  136,
      136,   82,  144,  144,   82,  137,   79,  376,  194,  375,

      194,  189,  138,  195,  195,  190,  374,  137,  136,  136,
      197,  197,  200,  373,  200,  372,  198,  201,  201,  202,
      202,  138,  371,  199,  216,  217,  227,  370,  198,  228,
      195,  195,  203,  252,  252,  197,  197,  255,  369,  255,
      368,  198,  256,  256,  197,  197,  253,  367,  199,  201,
      201,  257,  257,  198,  202,  202,  366,  199,  202,  202,
      252,  252,  252,  252,  258,  256,  256,  203,  297,  297,
      365,  203,  364,  253,  363,  253,  257,  257,  257,  257,
      362,  298,  297,  297,  297,  297,  361,  360,  359,  258,
      358,  258,  357,  356,  355,  298,  354,  298,   57,   57,

       57,   61,   61,   61,  134,  353,  134,  140,  352,  140,
      351,  350,  349,  348,  347,  346,  345,  344,  343,  342,
      341,  340,  339,  338,  337,  336,  335,  334,  333,  332,
      331,  330,  329,  328,  327,  326,  325,  324,  323,  322,
      321,  320,  319,  318,  317,  316,  315,  314,  313,  312,
      311,  310,  309,  308,  307,  306,  305,  304,  303,  302,
      301,  300,  299,  296,  295,  294,  293,  292,  291,  290,
      289,  288,  287,  286,  285,  284,  283,  282,  281,  280,
      279,  278,  277,  276,  275,  274,  273,  272,  271,  270,
      269,  268,  267,  266,  265,  264,  263,  262,  261,  260,

      259,  254,  251,  250,  249,  248,  247,  246,  245,  244,
      243,  242,  241,  240,  239,  238,  237,  236,  235,  234,
      233,  232,  231,  230,  229,  226,  225,  224,  223,  222,
      221,  220,  219,  218,  215,  214,  213,  212,  211,  210,
      209,  208,  207,  206,  205,  204,  196,  193,  185,  184,
      183,  180,  179,  178,  175,  174,  173,  172,  171,  168,
      167,  166,  165,  164,  163,  162,  161,  160,  159,  158,
      157,  156,  155,  152,  151,  150,  149,  148,  147,  146,
      145,  139,  133,  132,  131,  130,  129,  128,  120,  113,
      109,   88,   85,   70,   69,   67,   66,  385,    7,  385,

      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385
    } ;

static const flex_int16_t yy_chk[560] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    4,    3,    4,    5,    6,    5,    6,   24,    5,
        6,    3,    4,   25,   25,   26,   24,   30,   30,   27,
       26,   27,   27,   32,   32,   34,  388,   27,   38,  122,
       34,    5,    6,   28,   27,   28,   28,   25,   39,   27,

       39,   28,   40,   38,  122,   41,  382,   39,   28,   40,
      381,   43,   40,   28,   41,   40,   42,   48,   42,   43,
       65,   43,   45,   50,   43,  380,   47,   42,   45,   45,
       47,   51,   48,   50,   50,   48,   50,  379,   50,   51,
       80,   80,   65,  378,   47,  118,   73,   73,   77,   77,
      118,   65,   73,   80,   77,   96,   96,  377,   65,   73,
      128,   65,  128,   65,   73,   78,   77,   78,   78,   79,
      126,   79,  375,   78,   79,   79,   81,  126,   81,   81,
       78,   82,   82,  127,   81,   78,  112,  112,  374,  136,
      136,   81,  143,  143,   82,  136,   81,  373,  137,  372,

      137,  127,  136,  137,  137,  127,  371,  136,  138,  138,
      141,  141,  142,  370,  142,  367,  141,  142,  142,  144,
      144,  138,  366,  141,  157,  157,  168,  364,  141,  168,
      194,  194,  144,  195,  195,  197,  197,  198,  361,  198,
      360,  197,  198,  198,  199,  199,  195,  359,  197,  200,
      200,  201,  201,  197,  202,  202,  358,  199,  203,  203,
      252,  252,  253,  253,  201,  255,  255,  202,  256,  256,
      356,  203,  355,  252,  353,  253,  257,  257,  258,  258,
      352,  256,  297,  297,  298,  298,  351,  350,  347,  257,
      346,  258,  345,  344,  343,  297,  342,  298,  386,  386,

      386,  387,  387,  387,  389,  341,  389,  390,  338,  390,
      337,  336,  332,  330,  329,  328,  326,  325,  323,  321,
      317,  316,  315,  313,  312,  310,  309,  308,  306,  305,
      304,  302,  301,  299,  296,  294,  293,  292,  291,  290,
      288,  287,  285,  284,  283,  282,  281,  280,  279,  278,
      277,  276,  274,  272,  271,  270,  269,  264,  263,  262,
      261,  260,  259,  254,  251,  250,  247,  246,  244,  243,
      242,  241,  240,  239,  238,  237,  236,  235,  234,  232,
      230,  229,  228,  227,  225,  224,  223,  222,  219,  218,
      217,  216,  215,  213,  210,  209,  208,  207,  206,  205,

      204,  196,  193,  192,  191,  189,  188,  187,  186,  185,
      184,  183,  182,  181,  180,  179,  178,  177,  176,  175,
      174,  172,  171,  170,  169,  167,  165,  164,  163,  162,
      161,  160,  159,  158,  156,  155,  154,  153,  152,  151,
      150,  149,  148,  147,  146,  145,  139,  129,  125,  124,
      123,  121,  120,  119,  117,  116,  115,  114,  113,  111,
      109,  108,  107,  106,  105,  104,  103,  102,  101,  100,
       99,   98,   97,   95,   94,   93,   92,   91,   90,   89,
       88,   74,   63,   60,   59,   55,   53,   52,   49,   46,
       44,   33,   31,   22,   18,   14,   12,    7,  385,  385,

      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "jucompiler.l"
#line 2 "jucompiler.l"

    /*Lorando Ca e Augusto Hunguana*/


    /* place here any C variables and definitions */

    #include "y.tab.h"
    #include "ast1.h"
    #include "semantics.h"
    #include "codegen.h"
    #include <string.h>

    int PrintMatch( char *word); 
    void copiarString(char origem);
    
    /*igual ao petit.l:
    guardar o lexema reconhecido em yyval */
    #define PASS_TOKEN() yylval.lexeme = strdup(yytext)



    int yyparse(void);
    void yyerror(char *);

    int semantic_analisis = 0;

    int colAtual = 1;
    int linha = 1;
    int printall = 0;
    int printerrors = 0;
    int lex_errors = 0;
    int lineBackup = 0, colBackup = 0;
    char string[1024];
    char buffer[1024 + 3];
    int indice = 0, flag = 0;
    
    int syn_line = -1, syn_column = -1;
    int errors = 0;

    #define YY_USER_ACTION { \
        syn_line = linha; \
        syn_column = colAtual; \
        if(YYSTATE == INITIAL) colAtual += yyleng; \
        yylloc.first_line = syn_line; \
        yylloc.first_column = syn_column; \
    }

    extern struct node *ast;
    extern struct programs_list *handle;

static const char *category_names[] = {
    /* Nó raiz */
    "Program",

    /* Declarações */
    "FieldDecl",
    "VarDecl",

    /* Métodos */
    "MethodDecl",
    "MethodHeader",
    "MethodParams",
    "ParamDecl",
    "MethodBody",
    "Args",
    "Dummy", //Added to store nodes that had errors

    /* Statements */
    "Block",
    "If",
    "While",
    "Return",
    "Call",
    "Print",
    "ParseArgs",
    "Assign",

    /* Operadores binários */
    "Or",
    "And",
    "Eq",
    "Ne",
    "Lt",
    "Gt",
    "Le",
    "Ge",
    "Add",
    "Sub",
    "Mul",
    "Div",
    "Mod",
    "Lshift",
    "Rshift",
    "Xor",

    /* Operadores unários */
    "Not",
    "Minus",
    "Plus",

    /* Outros operadores */
    "Length",

    /* Tipos */
    "Bool",
    "Int",
    "Double",
    "Void",
    "StringArray",

    /* Terminais / Literais */
    "BoolLit",
    "Decimal",
    "Natural",
    "StrLit",
    "Identifier",
};


#line 809 "lex.yy.c"

#line 811 "lex.yy.c"

#define INITIAL 0
#define COMMENT 1
#define STRINGSTATE 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 134 "jucompiler.l"




#line 1035 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 386 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 499 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 138 "jucompiler.l"
{}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 139 "jucompiler.l"
{}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 140 "jucompiler.l"
{ colAtual = 1; linha ++;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 141 "jucompiler.l"
{}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 146 "jucompiler.l"
{}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 148 "jucompiler.l"
{BEGIN(COMMENT); lineBackup = syn_line; colBackup = syn_column;  }
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 149 "jucompiler.l"
{colAtual = 1; linha ++;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 150 "jucompiler.l"
{colAtual += yyleng;}
	YY_BREAK
case YY_STATE_EOF(COMMENT):
#line 151 "jucompiler.l"
{ if (printall || printerrors) printf("Line %d, col %d: unterminated comment\n", lineBackup, colBackup); 
                    lex_errors ++;
                    syn_line = linha;     
                    syn_column = colAtual;
                    BEGIN 0; 
                 }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 157 "jucompiler.l"
{
                colAtual += yyleng; 
                syn_line = linha;     
                syn_column = colAtual;
                BEGIN 0;    }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 169 "jucompiler.l"
{ BEGIN(STRINGSTATE); lineBackup = linha; colBackup = syn_column;  flag = 0; indice = 0; string[0]= '\0';}   /* inicia string */
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 172 "jucompiler.l"
{ char esc = yytext[yyleng - 1];
                                string[indice++] = '\\';
                                string[indice++] = esc;
                                string[indice] = '\0';
                                colAtual += 2; }/*escapes validos (mais especificos)*/
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 178 "jucompiler.l"
{ flag = 1; 
                            if(yytext[yyleng-1] == '\\') { 
                                if (printall || printerrors) printf("Line %d, col %d: invalid escape sequence (\\)\n", linha, syn_column); 
                                colAtual += 1;
                                lex_errors ++;

                            } else { 
                                if (printall || printerrors) printf("Line %d, col %d: invalid escape sequence (%s)\n", linha, syn_column, yytext); 
                                lex_errors ++;

                                colAtual += 2;
                            }
                            
                         }/*escapes invalidos*/
	YY_BREAK
case 13:
/* rule 13 can match eol */
YY_RULE_SETUP
#line 193 "jucompiler.l"
{ BEGIN INITIAL; if (printall || printerrors) printf("Line %d, col %d: unterminated string literal\n", lineBackup, colBackup); 
                                colAtual = 1; linha ++; string[0] = '\0';
                                syn_column = colBackup;
                                syn_line = lineBackup;
                                lex_errors ++;

                            }/*newlines*/
	YY_BREAK
case YY_STATE_EOF(STRINGSTATE):
#line 201 "jucompiler.l"
{BEGIN INITIAL;  if (printall || printerrors) printf("Line %d, col %d: unterminated string literal\n", lineBackup, colBackup); 
                                syn_column = colBackup;
                                syn_line = lineBackup;
                                colAtual = 1; linha ++; string[0] = '\0';
                                lex_errors ++;
                                }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 208 "jucompiler.l"
{ 
    colAtual++;
    BEGIN INITIAL; 
    if (flag == 0) {
        buffer[0] = '\0';
        sprintf(buffer, "\"%s\"", string);

        if (printall) printf("STRLIT(%s)\n", buffer);

        syn_column = colBackup;
        syn_line = lineBackup;

        // Passar a string já com aspas para o yylval
        yylval.lexeme = strdup(buffer); 
        yytext = buffer;
        return STRLIT; 
    } 
    string[0] = '\0'; 
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 228 "jucompiler.l"
{ copiarString(yytext[0]);  colAtual++;}/*texto normal*/
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 235 "jucompiler.l"
{ if (printall) PrintMatch("PRINT"); return PRINT; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 236 "jucompiler.l"
{ if (printall) PrintMatch("PARSEINT"); return PARSEINT;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 237 "jucompiler.l"
{ if (printall) PrintMatch("DOTLENGTH"); return DOTLENGTH;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 239 "jucompiler.l"
{ if (printall) PrintMatch("RESERVED(++)"); return RESERVED; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 240 "jucompiler.l"
{ if (printall) PrintMatch("RESERVED(--)"); return RESERVED; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 241 "jucompiler.l"
{ if (printall) PrintMatch("EQ"); PASS_TOKEN(); return EQ; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 242 "jucompiler.l"
{ if (printall) PrintMatch("NE"); PASS_TOKEN(); return NE; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 243 "jucompiler.l"
{ if (printall) PrintMatch("GE"); return GE; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 244 "jucompiler.l"
{ if (printall) PrintMatch("LE"); return LE; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 245 "jucompiler.l"
{ if (printall) PrintMatch("RSHIFT"); return RSHIFT; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 246 "jucompiler.l"
{ if (printall) PrintMatch("LSHIFT"); return LSHIFT; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 247 "jucompiler.l"
{ if (printall) PrintMatch("AND"); return AND; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 248 "jucompiler.l"
{ if (printall) PrintMatch("OR"); return OR; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 249 "jucompiler.l"
{ if (printall) PrintMatch("ARROW"); return RESERVED; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 251 "jucompiler.l"
{ if (printall) PrintMatch("ASSIGN"); PASS_TOKEN(); return ASSIGN; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 252 "jucompiler.l"
{ if (printall) PrintMatch("GT"); return GT; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 253 "jucompiler.l"
{ if (printall) PrintMatch("LT"); return LT; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 254 "jucompiler.l"
{ if (printall) PrintMatch("PLUS"); PASS_TOKEN(); return PLUS; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 255 "jucompiler.l"
{ if (printall) PrintMatch("MINUS"); PASS_TOKEN(); return MINUS; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 256 "jucompiler.l"
{ if (printall) PrintMatch("STAR"); PASS_TOKEN(); return STAR; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 257 "jucompiler.l"
{ if (printall) PrintMatch("DIV"); PASS_TOKEN(); return DIV; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 258 "jucompiler.l"
{ if (printall) PrintMatch("MOD"); return MOD; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 259 "jucompiler.l"
{ if (printall) PrintMatch("NOT"); return NOT; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 260 "jucompiler.l"
{ if (printall) PrintMatch("XOR"); PASS_TOKEN(); return XOR; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 261 "jucompiler.l"
{ if (printall) PrintMatch("COMMA"); return COMMA; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 262 "jucompiler.l"
{ if (printall) PrintMatch("SEMICOLON"); return SEMICOLON; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 263 "jucompiler.l"
{ if (printall) PrintMatch("LBRACE"); return LBRACE; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 264 "jucompiler.l"
{ if (printall) PrintMatch("RBRACE"); return RBRACE; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 265 "jucompiler.l"
{ if (printall) PrintMatch("LPAR"); return LPAR; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 266 "jucompiler.l"
{ if (printall) PrintMatch("RPAR"); return RPAR; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 267 "jucompiler.l"
{ if (printall) PrintMatch("LSQ"); return LSQ; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 268 "jucompiler.l"
{ if (printall) PrintMatch("RSQ"); return RSQ; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 270 "jucompiler.l"
{ if (printall) PrintMatch("IF"); return IF; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 271 "jucompiler.l"
{ if (printall) PrintMatch("ELSE"); return ELSE; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 272 "jucompiler.l"
{ if (printall) PrintMatch("WHILE"); return WHILE; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 273 "jucompiler.l"
{ if (printall) PrintMatch("RETURN"); return RETURN; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 274 "jucompiler.l"
{ if (printall) PrintMatch("STATIC"); return STATIC; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 275 "jucompiler.l"
{ if (printall) PrintMatch("PUBLIC"); return PUBLIC; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 276 "jucompiler.l"
{ if (printall) PrintMatch("CLASS"); return CLASS; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 277 "jucompiler.l"
{ if (printall) PrintMatch("VOID"); return VOID; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 278 "jucompiler.l"
{ if (printall) PrintMatch("INT"); return INT; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 279 "jucompiler.l"
{ if (printall) PrintMatch("DOUBLE"); return DOUBLE; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 280 "jucompiler.l"
{ if (printall) PrintMatch("BOOL"); return BOOL; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 281 "jucompiler.l"
{ if (printall) PrintMatch("STRING"); return STRING; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 283 "jucompiler.l"
{ if (printall) PrintMatch("BOOLLIT(true)"); PASS_TOKEN(); return BOOLLIT; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 284 "jucompiler.l"
{ if (printall) PrintMatch("BOOLLIT(false)"); PASS_TOKEN(); return BOOLLIT; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 285 "jucompiler.l"
{ if (printall) PrintMatch("RESERVED(null)"); return RESERVED; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 287 "jucompiler.l"
{ if (printall) PrintMatch("RESERVED(Integer)"); return RESERVED; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 288 "jucompiler.l"
{ if (printall) PrintMatch("RESERVED(System)"); return RESERVED; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 290 "jucompiler.l"
{ if (printall) PrintMatch("RESERVED(break)"); return RESERVED; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 291 "jucompiler.l"
{ if (printall) PrintMatch("RESERVED(byte)"); return RESERVED; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 292 "jucompiler.l"
{ if (printall) PrintMatch("RESERVED(case)"); return RESERVED; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 293 "jucompiler.l"
{ if (printall) PrintMatch("RESERVED(catch)"); return RESERVED; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 294 "jucompiler.l"
{ if (printall) PrintMatch("RESERVED(char)"); return RESERVED; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 295 "jucompiler.l"
{ if (printall) PrintMatch("RESERVED(const)"); return RESERVED; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 296 "jucompiler.l"
{ if (printall) PrintMatch("RESERVED(enum)"); return RESERVED; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 297 "jucompiler.l"
{ if (printall) PrintMatch("RESERVED(extends)"); return RESERVED; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 298 "jucompiler.l"
{ if (printall) PrintMatch("RESERVED(final)"); return RESERVED; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 299 "jucompiler.l"
{ if (printall) PrintMatch("RESERVED(finally)"); return RESERVED; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 300 "jucompiler.l"
{ if (printall) PrintMatch("RESERVED(float)"); return RESERVED; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 301 "jucompiler.l"
{ if (printall) PrintMatch("RESERVED(for)"); return RESERVED; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 302 "jucompiler.l"
{ if (printall) PrintMatch("RESERVED(implements)"); return RESERVED; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 303 "jucompiler.l"
{ if (printall) PrintMatch("RESERVED(import)"); return RESERVED; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 304 "jucompiler.l"
{ if (printall) PrintMatch("RESERVED(instanceof)"); return RESERVED; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 305 "jucompiler.l"
{ if (printall) PrintMatch("RESERVED(interface)"); return RESERVED; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 306 "jucompiler.l"
{ if (printall) PrintMatch("RESERVED(long)"); return RESERVED; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 307 "jucompiler.l"
{ if (printall) PrintMatch("RESERVED(native)"); return RESERVED; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 308 "jucompiler.l"
{ if (printall) PrintMatch("RESERVED(new)"); return RESERVED; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 309 "jucompiler.l"
{ if (printall) PrintMatch("RESERVED(protected)"); return RESERVED; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 310 "jucompiler.l"
{ if (printall) PrintMatch("RESERVED(short)"); return RESERVED; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 311 "jucompiler.l"
{ if (printall) PrintMatch("RESERVED(strictfp)"); return RESERVED; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 312 "jucompiler.l"
{ if (printall) PrintMatch("RESERVED(super)"); return RESERVED; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 313 "jucompiler.l"
{ if (printall) PrintMatch("RESERVED(this)"); return RESERVED; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 314 "jucompiler.l"
{ if (printall) PrintMatch("RESERVED(throw)"); return RESERVED; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 315 "jucompiler.l"
{ if (printall) PrintMatch("RESERVED(throws)"); return RESERVED; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 316 "jucompiler.l"
{ if (printall) PrintMatch("RESERVED(transient)"); return RESERVED; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 317 "jucompiler.l"
{ if (printall) PrintMatch("RESERVED(try)"); return RESERVED; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 318 "jucompiler.l"
{ if (printall) PrintMatch("RESERVED(volatile)"); return RESERVED; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 319 "jucompiler.l"
{ if (printall) PrintMatch("RESERVED(abstract)"); return RESERVED; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 320 "jucompiler.l"
{ if (printall) PrintMatch("RESERVED(continue)"); return RESERVED; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 321 "jucompiler.l"
{ if (printall) PrintMatch("RESERVED(switch)"); return RESERVED; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 322 "jucompiler.l"
{ if (printall) PrintMatch("RESERVED(assert)"); return RESERVED; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 323 "jucompiler.l"
{ if (printall) PrintMatch("RESERVED(default)"); return RESERVED; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 324 "jucompiler.l"
{ if (printall) PrintMatch("RESERVED(package)"); return RESERVED; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 325 "jucompiler.l"
{ if (printall) PrintMatch("RESERVED(synchronized)"); return RESERVED; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 326 "jucompiler.l"
{ if (printall) PrintMatch("RESERVED(do)"); return RESERVED; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 327 "jucompiler.l"
{ if (printall) PrintMatch("RESERVED(goto)"); return RESERVED; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 328 "jucompiler.l"
{ if (printall) PrintMatch("RESERVED(private)"); return RESERVED; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 331 "jucompiler.l"
{ 
    /*texto reconhecido para yylval.lexeme*/
PASS_TOKEN();
if( printall) printf ("IDENTIFIER(%s)\n", yytext);
return IDENTIFIER;
}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 340 "jucompiler.l"
{
    /*DECIMAIS*/
    PASS_TOKEN();
    if( printall) printf ("DECIMAL(%s)\n", yytext);
    return DECIMAL;
}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 347 "jucompiler.l"
{
    PASS_TOKEN();
    if( printall) printf ("DECIMAL(%s)\n", yytext);
    return DECIMAL;
}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 353 "jucompiler.l"
{
    PASS_TOKEN();
    if( printall) printf ("DECIMAL(%s)\n", yytext);
    return DECIMAL;
}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 359 "jucompiler.l"
{
    PASS_TOKEN();
    if( printall) printf ("DECIMAL(%s)\n", yytext);
    return DECIMAL;
}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 365 "jucompiler.l"
{
    PASS_TOKEN();
    if( printall) printf ("DECIMAL(%s)\n", yytext);
    return DECIMAL;
}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 372 "jucompiler.l"
{
    PASS_TOKEN();
    if( printall) printf ("NATURAL(%s)\n", yytext);
    return NATURAL; 
}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 379 "jucompiler.l"
{ if (printall || printerrors) printf("Line %d, col %d: illegal character (%s)\n",  linha, syn_column, yytext); lex_errors ++;}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 381 "jucompiler.l"
{ YY_USER_ACTION; return 0; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 385 "jucompiler.l"
ECHO;
	YY_BREAK
#line 1752 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 386 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 386 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 385);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 385 "jucompiler.l"


#include <stdio.h>


int PrintMatch(char *word){
    printf("%s\n", word);
    return 0;
}


void copiarString(char c) {
    // Em vez de guardar o caractere processado
    // guarda a representação textual original
    if(c == '\\') { string[indice++] = '\\'; string[indice++] = '\\'; }
    else if(c == '"') { string[indice++] = '\\'; string[indice++] = '"'; }
    else { string[indice++] = c; }
    string[indice] = '\0';
}

void yyerror (char *s) {
    printf ("Line %d, col %d: %s: %s\n", syn_line, syn_column, s, yytext);
    errors++;
}



void show_no_types(struct node *no, int depth) {
    if (no == NULL) return;

    const char *name = category_names[no->category];
    if (name == NULL) name = "UNKNOWN";

    int next_depth = depth;

    if(strcmp(name, "Args") != 0 && strcmp(name, "Dummy") != 0) {
        
        for (int i = 0; i < 2 * depth; i++) printf(".");

        if (no->token != NULL)
            printf("%s(%s)\n", name, no->token);
        else
            printf("%s\n", name);
        
        next_depth = depth + 1;
    }

    struct node_list *atual = no->children;
    while (atual != NULL) {
        if (atual->node != NULL)
            show_no_types(atual->node, next_depth);
        atual = atual->next;
    }
}

void show(struct node *no, int depth) {

    if(semantic_analisis && errors > 0){ show_no_types(no, depth); return; }
    if (no == NULL) return;

    const char *name = category_names[no->category];
    if (name == NULL) name = "UNKNOWN";

    int next_depth = depth;

    if(strcmp(name, "Args") != 0 && strcmp(name, "Dummy") != 0) {
        
        for (int i = 0; i < 2 * depth; i++) printf(".");

        if (no->token != NULL && !ignoreOp(no->category)) {
            if (no->args != NULL)
                printf("%s(%s) - %s\n", name, no->token, no->args);
            else if (no->visit == 1 && no->varDecl != 1 && is_operation(no->category) && !ignore(no->type))
                printf("%s(%s) - %s\n", name, no->token, type_name(no->type));
            else
                printf("%s(%s)\n", name, no->token);
        } else {
            if (no->visit == 1 && no->varDecl != 1 && is_operation(no->category) && !ignore(no->type))
                printf("%s - %s\n", name, type_name(no->type));
            else
                printf("%s\n", name);
        }
        
        next_depth = depth + 1;
    }

    struct node_list *atual = no->children;
    while (atual != NULL) {
        if (atual->node != NULL) {
            if (!no->visit) atual->node->visit = 0;
            show(atual->node, next_depth);
        }
        atual = atual->next;
    }
}




// Flags de controlo
int print_tokens = 0;      // -l
int lex_errors_only = 0;   // -e1
int print_ast = 0;         // -t
int syntax_errors_only = 0;// -e2
int print_semantics = 0;   // -s
int semantic_errors_only = 0; // -e3
int gen_llvm = 1;          // Ativo por defeito, desativado se houver flags

// Contadores de erros (devem ser incrementados no .l, .y e semantics.c)
// errors -> syntatic errord
// return of check_program -> semantic errors


int main(int argc, char *argv[]) {
    // 1. Processamento de Argumentos
    if (argc > 1) {
        gen_llvm = 0; // Se houver qualquer flag, não gera LLVM
        if (strcmp(argv[1], "-l") == 0) {
            print_tokens = 1;
            printall = 1;
            printerrors = 1;
        } else if (strcmp(argv[1], "-e1") == 0) {
            printerrors = 1;
        } else if (strcmp(argv[1], "-t") == 0) {
            print_ast = 1;
        } else if (strcmp(argv[1], "-e2") == 0) {
            syntax_errors_only = 1;
        } else if (strcmp(argv[1], "-s") == 0) {
            print_semantics = 1;
        } else if (strcmp(argv[1], "-e3") == 0) {
            semantic_errors_only = 1;
        }
    }

    // 2. Execução conforme a Flag
    
    // Caso -l ou -e1: Apenas análise lexical
    if (print_tokens || lex_errors_only) {
        while (yylex() != 0); // O yylex deve imprimir tokens se uma flag global 'print_tokens' estiver ativa
        return 0;
    }

    // Caso -t, -e2, -s, -e3 ou Geração de Código: Requer análise sintática (yyparse)
    int parse_result = yyparse(); 

    int syntax_errors = errors, lexical_errors = lex_errors, semantic_errors;

    // Se houver erros lexicais ou sintáticos, paramos aqui para as flags de sintaxe
    if (parse_result != 0 || syntax_errors > 0 || lexical_errors > 0 ) {
        if (print_ast) {
            // Se -t e houver erro, o enunciado diz para não imprimir a árvore
            return 0; 
        }
        // Para -e2, -e3 e -s, o comportamento em erro sintático é o mesmo: reportar erros e terminar
        return 0;
    }

    // 3. Análise Semântica (Apenas se não houver erros sintáticos/lexicais)
    if (print_semantics || semantic_errors_only || gen_llvm) {
        // Assume-se que esta função faz o check e anota a AST
        semantic_errors = check_program(ast); 

        if (print_semantics) {
            show(ast, 0);
            return 0;
        }
        
        if (semantic_errors_only) {
            // Apenas reporta erros (já feito dentro do check_semantics)
            return 0;
        }
    }

    // 4. Geração de Árvore Sintática (Flag -t)
    if (print_ast) {
        show(ast, 0); // Imprime AST simples
        return 0;
    }

    // 5. Geração de Código LLVM IR
    // Só chega aqui se gen_llvm for 1 (sem flags) E não houve erros lexicais, sintáticos ou semânticos
    if (gen_llvm && lexical_errors == 0 && syntax_errors == 0 && semantic_errors == 0) {
        generate_llvm_ir(ast);
    }

    return 0;

}

int yywrap() {  /* called on EOF, return 1 to terminate */
    return 1;
}

